FROM python:3.11-slim
ENV PYTHONDONWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y curl build-essential libpq-dev && apt-get clean

RUN pip install --upgrade pip
RUN pip install poetry

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi


COPY . .


EXPOSE 8000

CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]